### ISSUE TITLE
Question: Is there a way to toggle the enabled state of a fault?

### ISSUE THREAD

**Issue by clarktlaugh** [github/go-fault#12]
I would like to be able to control (at runtime) whether this fault injection is working.

**Comment by lingrino** [comment]
👋 @clarktlaugh there's not currently a built in way to toggle a fault at runtime but I do think that's a great addition to this package. Would something like `fault.SetParticipation()` work? For off/on you could set it to `0.0`/`1.0` or any value in between.

**Comment by clarktlaugh** [comment]
> 👋 @clarktlaugh there's not currently a built in way to toggle a fault at runtime but I do think that's a great addition to this package. Would something like `fault.SetParticipation()` work? For off/on you could set it to `0.0`/`1.0` or any value in between.

I think that would be fine.  I'm just looking to be able to build this into a production system and give myself the ability to turn it on and off on the fly.

Thank you!

**Comment by lingrino** [comment]
I'll track the work for this here - https://github.com/github/go-fault/issues/13
