### ISSUE TITLE
Please remove DATADOG_API_KEY secret

### ISSUE THREAD

**Issue by seveas** [github/go-fault#25]
There is now an org-wide secret with that name and a per-repository secret is no longer needed. Please remove this secret from the repository settings and ask @github/observability to revoke it once it has been removed. Thanks!

cc https://github.com/github/observability/issues/2339

**Comment by lingrino** [comment]
Oh hello @seveas!! This is a public repo by the way 😄. I just removed the token and the whole integration with datadog since I assume the metrics have been unused at GitHub for a long time. PR is https://github.com/github/go-fault/pull/26. I hope you're doing well!

**Comment by seveas** [comment]
Hi @lingrino!

Thanks for removing this bit of legacy, I like clean repos :)
